apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dorji-deploy
  name: dorji-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dorji-deploy
  template:
    metadata:
      labels:
        app: dorji-deploy
    spec:
      containers:
      - image: dzangmo/newpet:latest
        name: pet
